### PR TITLE
Modularize parseTokenList and ignore empty http tokens. Fixes #32

### LINKED ISSUE #32: fresh is not ignoring empty http tokens
It appears that fresh has copy-pasted logic from `send` related to etag handling.

This commit should probably be copied in it's entirety over to fresh, right? :
https://github.com/pillarjs/send/commit/aeb69c607bd01be2009c1ec822dab36151544421

It does raise the question if it might be possible to package up in a more re-usable way since there is some overlap between parts of the internals of `fresh (req, res)`  and `send`'s `isPreconditionFailure`.  Or perhaps they are just different enough to warrant the duplication.

Anyway, if you agree that this commit should be copied over from `send` happy to send a PR.

thanks for these 2 fantastic modules by the way!  ❤️   I'm working on improving koa's range support and `send`, `fresh` have both been incredibly rich sources towards better compliance with rfc7233, rfc 7232

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Review by dougwilson — CHANGES_REQUESTED** [review]
Hi @mreinstein thank you for your pull request. Can you please put the token stuff back in `index.js`? Our module policy is that we only have a single `index.js` file in each of our modules -- no extra files, as people can import those and we end up with people using them outside of our control (i.e. `require('fresh/parse-token-list')`. Modules that have multiple files are just for legacy reasons.

**Comment by mreinstein** [comment]
I certainly can do that, but I'm unclear how to expose it sufficiently for unit testing at that point. What do you suggest?

**Comment by dougwilson** [comment]
> I certainly can do that, but I'm unclear how to expose it sufficiently for unit testing at that point. What do you suggest?

We only test the public API. If the changes don't affect the actual public API functionality, what is the purpose of the changes?

**Comment by mreinstein** [comment]
> what is the purpose of the changes? 

To ensure that a given "unit" (in this case a function) is behaving correctly, regardless of how it's results get composed into a public result.

**Comment by dougwilson** [comment]
> To ensure that a given "unit" (in this case a function) is behaving correctly, regardless of how it's results get composed into a public result.

I mean, it is behaving correctly if it results in correct behavior in the public API. It would be behaving incorrectly if it caused incorrect behavior in the public API. Maybe a different way, how would a user who uses this module be affected by the "incorrect behavior of the parseTokenList function"?

**Comment by mreinstein** [comment]
>  it is behaving correctly if it results in correct behavior in the public API

completely correct. 👍 

> how would a user who uses this module be affected by the "incorrect behavior of the parseTokenList function"?

a user would _not_ be affected today by this, but a developer in the future tasked with maintaining `fresh` may not be aware that `parseTokenList` isn't guarding against empty http tokens, and then introduce an issue that _does_ affect the user.

**Comment by mreinstein** [comment]
maybe the solution is to simply drop the unit tests and keep the guard?

**Comment by dougwilson** [comment]
Regardless, like I mentioned, I would be happy to accept the copy-paste, but it needs to be in the `index.js` file is all I requested the change of the PR...

> a user would not be affected today by this, but a developer in the future tasked with maintaining fresh may not be aware that parseTokenList isn't guarding against empty http tokens, and then introduce an issue that does affect the user.

If that is the concern, let's make sure we have tests that includes empty tokens to prevent such a regression.

**Comment by dougwilson** [comment]
Hi @mreinstein why did you close this? I'm really sorry if I offended you or something... I said just copy pasting in I'd be happy to accept in that PR. I'll go ahead and push up the change since it seems like you closed the PR

**Comment by mreinstein** [comment]
> why did you close this? I'm really sorry if I offended you or something

You definitely did _not_ offend me, I opened a clean PR with the more limited change that you asked for. :)

Personally I don't agree; I think that testing the public interface is what is more commonly known as an integration test, but I am just trying to respect the conventions within the jshttp org and get shit done. :)

**Comment by mreinstein** [comment]
see https://github.com/jshttp/fresh/pull/34

**Comment by mreinstein** [comment]
> I'm just guggling a few things ATM.

You're _always_ juggling many things. :-) I know you've been heavily involved in the expressjs stuff for quite a while. And I must say thank you again for all of that work, and all of the common http related modules to be found within pillar & httpjs! They are a huge help. ❤️

**Comment by dougwilson** [comment]
Yea, we don't do unit tests, because everything we export someone can import and we have gotten burned many times with security vulnerability from internal functions that folks imported and used for something we didn't intend. The JS community is very trigger happy with security vulnerabilities and the module authors have no say in what is/is not a vulnerability, so we are very careful on how we manage our modules any longer. Of course, no one will ever agree with everything other people do -- like even or code style. But it is what it is :)

And I don't want to come off and non-receptive to changes, either. I know I can struggle though text to fully express my intentions. I love that you are opening issues, PRs, having conversations about things...

**Comment by mreinstein** [comment]
> so we are very careful on how we manage our modules any longer

That's fair, and definitely not something most people have to deal with. Many of the modules you folks are maintaining have 100M+ downloads so I get that. 

> no one will ever agree with everything other people do
Naturally. And I'm not trying to wage a big battle to make some changes. Especially on this particular PR which has absolutely no consequence on the public result, only a subtle maintenance impact. :)


> I don't want to come off and non-receptive to changes, either. 

Ok I will open myself to get shot down here then. :) Possibly palatable but have you folks considered a very "light" build step?  The source could define pure es modules, and then use a tool like esbuild to bundle it up into a single commonjs output. This would have some nice effects:
* keep modules as single file with a very controlled public API
* enable moving to the ESM standard, which makes it easier to mix/match/re-use those modules internally within jshttp/pillar/express/koa
* enable unit tests as desired

Just to be clear I generally abhor build steps in js (you have no idea how many typescript zealots I get knocking on the doors of my much less popular projects :) ) but in this case bundling into a single file might make a lot of sense.

**Comment by dougwilson** [comment]
We have somewhat, but the main hold back so far has been that there are various security softwares that will score the modules lower/show alerts when the git source doesn't match what is in the npm tarball, sites like jsdelivr (though i think they offer npm tarballs now) and stuff allow folks to use the modules right from the git repo and other stuff that made it when we tried for a bit, we got constant issues asking for the build output to be checked in to the repo, but that creates just more confusion, as people then make PRs against the build output items and stuff... also had quite a few publishes where the person forgot to build and so it was some broken package... we haven't found a good solution yet that actually satisfies everyone, so it has just been cjs modules with no build steps currently. I'm sure it's all solvable, but just haven't had anyone interested to actually solve all the issues at hand; just like ton hand wave away whatever concerns is inconvenient and so no one contributes a solution, lol. The js ecosystem is quite a mess anyone, especially with the es module stuff.

**Comment by mreinstein** [comment]
> the main hold back so far has been that there are various security softwares that will score the modules lower/show alerts when the git source doesn't match what is in the npm tarball

Wow, I didn't even know that security software was doing that! 🤔    Another example of "modern" programming, where we worship automated tools with broken behavior because automation at all costs is the solution to everything apparently. 🥇 

>  just haven't had anyone interested to actually solve all the issues at hand; just like ton hand wave away whatever concerns is inconvenient and so no one contributes a solution, lol

You're preaching to the choir. :) If we spent half as much time on low level problems as we do on vanity code formatting etc. we would be much further along overall. I spent most of yesterday and today fully reading rfcs and no wonder people avoid that stuff like the plague and hand-wave away details. It is monstrously complex (like the HTTP `Vary` header anyone? :) )

> The js ecosystem is quite a mess anyone, especially with the es module stuff.

I agree, but I do think it will get better re: modules as commonjs and IIFEs drop away.  It seems that most of the complexity comes from wanting/needing to have hybrid cjs/esm behavior, and if/when we ever get to the point where we can focus 100 on esm a lot of that cruft will fall away.

**Comment by mreinstein** [comment]
> forgot to add that the current idea around es modules is just to convert everything over to es modules instead of cjs and release like that. 

That's the exact strategy I've been using/advocating in my own modules. This is the kind of thing that semver major is invented for.   For packages that have somewhat stabilized, switch fully to esm, bump semver major, and nothing breaks, except for people that blindly update their module deps with breaking changes and can't/don't test the results.

**Pull request closed without merging**
