### PR TITLE
Support upcoming changes in node

### PR DESCRIPTION
**Pull request by mscdex**

### CODE REVIEW

**Comment by dougwilson** [comment]
Thanks, but I don't understand why the change is necessary. You can see on the README the expected object for what a user should be passing in. They shouldn't be passing in anything where the value is an array.

**Comment by mscdex** [comment]
The issue is that `express` is blindly passing `res._headers` as the second argument to `fresh()`. I can submit a PR to `express` that basically makes a clone of `._headers` with string values before passing to `fresh()`, but I figured that would both be "expensive" and there may be others using `fresh` similarly and changing it one spot would be easier/better.

**Comment by dougwilson** [comment]
I mean, that sounds like those module are where the change belongs, because this module has never documented ever being able to pass in that object (also not tested). If those modules upstream wanted to take a short cut that was working, that's fine, but if their shortcut stopped working, they should change it there.

Because even this, this PR would then be missing the documentation to document that the objects passed in could now take arrays, which once you document the API looks like that, it doesn't really even make sense any longer...

**Comment by mscdex** [comment]
Alright, will open a PR against `express` then.

**Comment by dougwilson** [comment]
Gotcha. I look at express with blame and it looks like express has done that basically _forever_, lol. I know I've seen usages of `res._headers` in other places, especially in code created before `res.getHeader` existed, so I wouldn't be surprised if other things are affected similarly. Where can I see the changes made to the storage of `res._headers`?

I know times where I have personally reached for `res._headers` was a simple way to enumerate all the headers in a response, and I don't see any public replacement for that. Do you know how much core (at least on npm) has been reaching for `_headers` to at least have some kind of replacement public API? I know it's a private API and shame on code that uses it, of course, but sometimes there isn't another immediate option :/

Also, what version of Node.js is this change in (or is it just pending in a PR somewhere)?

**Comment by mscdex** [comment]
Node PR is at: https://github.com/nodejs/node/issues/10558

You can still iterate over it (although it *is* private) like before, but the thing that changed is the value. Basically instead of storing the original cased header names in a separate object (`._headerNames`), they're now stored alongside the value in `._headers` in an array. For example: `{ etag: ['ETag', '12345'] }`. A public API that returns a stable view of the request/response headers is the way forward (like how we do with `eventEmitter.listeners()`). If you want to submit a PR to add such functionality, go for it. Otherwise I may do so whenever I get a chance next.

Currently the change is only in master and I've labeled it as semver-major now. So it would be in v8.0.0 at the *earliest*.

**Comment by mscdex** [comment]
FWIW I went ahead and submitted a PR to add a `.getHeaders()` method to allow users to avoid having to resort to accessing a private/underscored property: https://github.com/nodejs/node/pull/10805

**Pull request closed without merging**
